
#duration app
#24 h = 86 400 secondes
total_duration : 86400
time_interval : 10

#signal
interval_list : ['1m', '5m', '15m', '30m', '1h', '2h', '4h', '1d', '1W', '1M']
interval_main : "5m"

#trade
new_futures_amount : 2000
leverage : 50
sell_seq : 3
buy_seq : 3

#control
minute_pause : 1
minimum_balance : 100000
maximum_trades : 45

##condition declencher perte(stoploss)
#sequence dans le sens contraire
nb_seq_reversal : 2
#stoploss via pnl - doit etre plus haut que margin
pnl_loss : -0.60

#pnl apres frais cible
target : 0.03

##pnl qui declenche ajout a la marge - au cas ou
min_margin : -0.80
add_margin_amount : 1000
#sous ce niveau, on ajoute pas a la marge - not used
min_leverage : 25








