
#duration app
#24 h = 86 400 secondes
total_duration : 86400
time_interval : 45

#signal
interval_list : ['1m', '5m', '15m', '30m', '1h', '2h', '4h', '1d', '1W', '1M']
interval_main : "5m"

#trade
add_margin_amount : 1000
new_futures_amount : 2000
leverage : 100
sell_seq : 3
buy_seq : 3

#control
minute_pause : 60
minimum_balance : 100000
maximum_trades : 45

#analyse
target : 0.10
min_margin : -0.60